Added buttons for endorsing/unendorsing topic
CMU-313/nodebb-frontend-f24-team-software-stars pull request #1
Opened 2024-10-08 21:04 UTC by ldlin1

Added buttons for both endorsing and unendorsing a topic. This was done by modifying templates/partials/topic/topic-menu-list.tpl file, which added these buttons alongside the other buttons in the Topic Tools dropdown menu. 

Currently the buttons don't work (they copy the functionality pinning/unpinning a topic), though I will connect the buttons to backend logic soon.

2024-10-09 00:58 UTC, etong11 requested changes
We should probably use different/new components than `topic/tag` to keep our code base organized. I think labeling the button as a different component won't require much additional code (I do believe that maybe another drop-down element with this component might need to be added in `templates/partials/category/tools.tpl` to replicate the functionality of the button). Using a different component might also be necessary when trying to hook up the back-end later on.

2024-10-10 02:12 UTC, etong11 approved these changes

2024-10-10 02:30 UTC, etong11 commented
Added onto Lu's changes by modifying `templates/partials/topic/topic-menu-list.tpl` with component names `topic/endorse` and `topic/unendorse`. These component names were changed to match the component names in the back-end code that handle the logic for hiding these components when the endorse action is called. Modified these buttons to switch between the endorsed/unendorsed option depending on the topic's endorse value (stored in the database).

Also added a label of endorsed that shows up when a topic is marked as endorsed with other labels such as locked in `templates/topic.tpl`.

Copied similar changes to `templates/partials/category/tools.tpl` and `templates/partials/topics_list.tpl` to add the endorse/unendorse tool/button to the category toolbar.

The UI changes for endorsements was completed by replicating the functionality of lock and pin which are other topic tools that exist in the same files that were changed. The functionality of these two features were also replicated in category tools as well.

2024-10-11 00:59 UTC, veronicabenedict approved these changes
Changes made to the files look good for the UI implementation, and is ready to be merged to main!

2024-10-11 00:59 UTC, merged

2024-10-11 02:20 UTC, ldlin1 commented
**Updated UI Images**

The following screenshots show the updated thumsb up/thumbs sideways icons

<img width="721" alt="Screenshot 2024-10-10 at 10 19 13 PM" src="https://github.com/user-attachments/assets/fe3ee0f8-36e7-4f56-92fd-ff39a9b05a1f">

<img width="721" alt="Screenshot 2024-10-10 at 10 19 00 PM" src="https://github.com/user-attachments/assets/b4794c89-4b4c-4f39-bc2a-0ec5a47ac41e">

<img width="722" alt="Screenshot 2024-10-10 at 10 18 30 PM" src="https://github.com/user-attachments/assets/bd5604f4-4b94-48e3-9f0c-61db87fc9e7d">

<img width="724" alt="Screenshot 2024-10-10 at 10 18 18 PM" src="https://github.com/user-attachments/assets/12821820-f62b-45a3-9bed-426aa381e374">

<img width="723" alt="Screenshot 2024-10-10 at 10 17 58 PM" src="https://github.com/user-attachments/assets/103bbe13-7db9-4706-8485-a1c50a59ce37">